name: Evaluation

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    timeout-minutes: 4

    if: github.event.pull_request.draft == false

    services:
      mssqlserver:
        image: mcr.microsoft.com/mssql/server:2017-CU17-ubuntu
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "xE4AK2J1uaMcm4qW"
          MSSQL_PID: "express"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check neptun.txt
        uses: akosdudas/ahk-action-neptuncheck@v1

      - name: Evaluate
        uses: docker://ghcr.io/bmeviauac01/sflab-ahk:mssql-2022
        env:
          DATABASE_CONNECTIONSTRING: "Server=mssqlserver;User id=sa;Password=xE4AK2J1uaMcm4qW"

      - name: Publish result
        uses: docker://ghcr.io/akosdudas/ahk-publish-results-pr:v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AHK_IMAGEEXT: ".png"
          AHK_APPTOKEN: "${{ secrets.AHK_APPTOKEN }}"
          AHK_APPSECRET: "${{ secrets.AHK_APPSECRET }}"
